function Hd = filter
%FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 16-Feb-2016 14:04:13

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 8000;  % Sampling Frequency

Fstop1 = 375;              % First Stopband Frequency
Fpass1 = 450;              % First Passband Frequency
Fpass2 = 1600;             % Second Passband Frequency
Fstop2 = 1750;             % Second Stopband Frequency
Dstop1 = 0.0039810717055;  % First Stopband Attenuation
Dpass  = 0.023021782436;   % Passband Ripple
Dstop2 = 0.0039810717055;  % Second Stopband Attenuation
dens   = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

save filename.txt b -ASCII -DOUBLE -TABS



% [EOF]
